theme: jekyll-theme-cayman
title: BKT Toolbox
description: Business Kasper Toolbox for Microsoft Office and PowerPoint
google_analytics: UA-4449782-16
show_downloads: false
lang: de
plugins:
  - jemoji